spring.application.name=stochedge-backend
server.port=8080

quant.engine.executable=../cpp-engine/build/stochedge_engine.exe
quant.engine.arguments=--json
quant.engine.timeout-seconds=90

market.data.yahoo-chart-url=https://query1.finance.yahoo.com/v8/finance/chart/
market.data.stooq-download-url=https://stooq.com/q/d/l/
market.data.twelve-data-url=https://api.twelvedata.com/time_series
market.data.twelve-data-api-key=demo
